version: "3.7"

services:
  notes-db:
    image: mysql:latest
    container_name: notes_db
    restart: always
    networks:
      - notes-network
    ports:
      - "3306:3306"
    env_file:
      - ../dev/.env
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 3

  notes-back:
    build:
      context: ../../EfecteBack/
    container_name: notes_back
    restart: always
    depends_on:
      - notes-db
    networks:
      - notes-network
    ports:
      - "8080:8080"
      - "5005:5005" #remote debug
    environment:
      - spring.datasource.url=jdbc:mysql://notes-db:3306/efectenotes
    env_file:
      - ../dev/.env

  notes-front:
    build:
      context: ../../EfecteFront/
      dockerfile: Dockerfile-dev
    container_name: notes_front
    restart: always
    depends_on:
      - notes-back
    networks:
      - notes-network
    ports:
      - "80:80"
    volumes:
      - "/app/node_modules"
      - ".:/app"

networks:
  notes-network: