spring:
  liquibase:
    change-log: classpath:/database/liquibaseChangelog.xml
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://localhost:3306/efectenotes?createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: update